### ISSUE TITLE
fatalerror　直し

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#12]

**Comment by ShinokiRyosei** [comment]
スクショちょうだい
コメント欄にスクショドラッグ&ドロップしたら貼り付けられるから、スクショください

**Comment by sotakenmotsu** [comment]
<img width="1280" alt="2017-01-20 22 00 46" src="https://cloud.githubusercontent.com/assets/19428366/22150355/f2c18eda-df5b-11e6-86ad-27061437057d.png">

**Comment by ShinokiRyosei** [comment]
2つの画面どっちも`RecruitmentViewController`になってるけど、どっちが`RecruitmentViewController`なの？
今左側の`RecruitmentViewController`がまずインスタンス化されるから、左側だと`LevelSelector`って関連付けされてないよね？
そこまずおかしくない？

次に、`pickerView`って`viewDidLoad`でしか使われてないから、
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let pickerView: UIPickerView = UIPickerView()
        pickerView.delegate = self
        pickerView.dataSource = self
        pickerView.showsSelectionIndicator = true
        
        let toolbar = UIToolbar(frame: CGRectMake(0, 0, 0, 35))
        let doneItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(RecruitmentViewController.done))
        let cancelItem = UIBarButtonItem(barButtonSystemItem: .cancel, target: self, action: #selector(RecruitmentViewController.cancel))
        toolbar.setItems([cancelItem, doneItem], animated: true)
        
        self.LevelSelector.inputView = pickerView
        self.LevelSelector.inputAccessoryView = toolbar
    }
```
と言うかたちで、`viewDidLoad`内だけで、かつ定数で宣言してあげよう
<img width="792" alt="2017-01-21 0 14 13" src="https://cloud.githubusercontent.com/assets/11238461/22154377/9e3c4522-df6e-11e6-9c37-d5934f4f8ce5.png">

**Comment by sotakenmotsu** [comment]
<img width="1280" alt="2017-01-21 22 26 48" src="https://cloud.githubusercontent.com/assets/19428366/22174731/bee7d808-e028-11e6-92ed-db08e1bbad27.png">
できた
ありがとうございます

**Comment by ShinokiRyosei** [comment]
Nice! Good Job!

**Comment by ShinokiRyosei** [comment]
@sotakenmotsu GitHubにコミットしてプッシュしておいてね
