### ISSUE TITLE
人数指定　pickerview　作成

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#14]
二つ目のpickerviewでどこを二つ作って、どこを二つ作らなくていいのかわからない
そのエラーだと思う
<img width="1280" alt="2017-01-22 20 11 14" src="https://cloud.githubusercontent.com/assets/19428366/22182089/562c7ba4-e0df-11e6-89ac-542cc3c63547.png">
<img width="1280" alt="2017-01-22 20 11 21" src="https://cloud.githubusercontent.com/assets/19428366/22182090/564ef198-e0df-11e6-8235-996b87dbd9b9.png">

**Comment by ShinokiRyosei** [comment]
エラーメッセージを日本語に訳すとどういう意味

**Comment by ShinokiRyosei** [comment]
かな？

**Comment by sotakenmotsu** [comment]
![2017-01-22 21 52 23](https://cloud.githubusercontent.com/assets/19428366/22182619/1497bb46-e0ed-11e6-98a4-dcba0b48cbb9.png)

**Comment by ShinokiRyosei** [comment]
ということは、どの変数が`nil`か調べないといけないよね？
Xcodeの右下の黒い画面がXcodeのコンソールなんだけど、そこで`po 変数名`ってするとその変数がnilなのかあるいはなにかしらの値が入ってるかわかるから、それでまずはなにが`nil`の変数か調べよう
<img width="1167" alt="2017-01-22 22 01 26" src="https://cloud.githubusercontent.com/assets/11238461/22182665/616e70d0-e0ee-11e6-9ce3-3962f197a6b2.png">

**Comment by ShinokiRyosei** [comment]
それでなにを2つにしないといけないかというと`UIPickerViewDelegate`と`UIPickerViewDataSource`のメソッドの中で`if文`で分岐してあげればいいよ

例えば、
```swift
func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
    if pickerView == LpickerView {
        return Llist.count
    }else {
        return Mlist.count
    }
}
```

**Comment by ShinokiRyosei** [comment]
そうたはマークダウンちゃんと使えるはずだから、変数名とは書く時はきちんと`こんな感じ`で囲って見やすいコメント書くことを心がけよう
おれはメンターだから、別にどんな聞き方してもいいけど、他人に質問する時は相手にできるだけちゃんと伝わるように、相手のことを思いやって質問しよう。お願いしているのはどっちかって大事だからね。

例えば、
> 二つ目のpickerviewでどこを二つ作って、どこを二つ作らなくていいのかわからない
そのエラーだと思う

という質問も
> 二つ目の`UIPickerView`でどこを二つ作って、どこを二つ作らなくていいのかわからない
そのエラーだと思う

という感じで書こう

ほかにも、
> エラーメッセージを日本語に訳すとどういう意味かな？

っていう質問をした時も、Google翻訳をそのまま出すのはいいけど、Macの全画面をスクショするよりも画面のうちで翻訳されてる部分だけでいいよね？そっちのほうが見やすくない？
こういうスクショにしてって意味ね。
<img width="650" alt="2017-01-22 22 14 17" src="https://cloud.githubusercontent.com/assets/11238461/22182737/391ee018-e0f0-11e6-897e-894b733191e0.png">
もっというとその文字をコメントにコピペでもいいよね？
> こういう意味やった。「致命的なエラー：オプション値をアンラッピングしている間に予期せずnilが見つかりました。」
だから、エラーが出てる行のどれかが`nil`になってるんだと思う。

こう書くほうがより見やすいよね？

**Comment by ShinokiRyosei** [comment]
言い忘れたけど、家でも開発してるのめっちゃうれしい
これからもその調子でどんどんやっていこう

**Comment by sotakenmotsu** [comment]
Xcodeのコンソールにうまく打ち込めない。
```
Filter
```
ってところに
```
po 変数名
```
て打つの？

**Comment by sotakenmotsu** [comment]
markdown間違えた

**Comment by ShinokiRyosei** [comment]
おれが貼ったスクリーンショットで黒い画面あるよね？

**Comment by sotakenmotsu** [comment]
<img width="188" alt="2017-01-22 22 36 36" src="https://cloud.githubusercontent.com/assets/19428366/22182867/5c241ddc-e0f3-11e6-93cc-52838166d973.png">

`MemberSelector`が `nil `みたい

**Comment by ShinokiRyosei** [comment]
```
(lldb)
```
のあとに、`po 変数名`って打てばいいよ
例えば、
```shell
(lldb) po Llist
```
という感じ

**Comment by ShinokiRyosei** [comment]
OK

**Comment by sotakenmotsu** [comment]
今日はもう寝ます

**Comment by ShinokiRyosei** [comment]
`MemberSelector`ってどうやって宣言されてる？

**Comment by ShinokiRyosei** [comment]
OK
また時間のあるときにやろう

**Comment by sotakenmotsu** [comment]
<img width="335" alt="2017-01-23 21 24 50" src="https://cloud.githubusercontent.com/assets/19428366/22203872/6f4d706a-e1b2-11e6-8c52-45c88cec2ec8.png">

関連付けしてないだけだった

**Comment by sotakenmotsu** [comment]
完成

**Comment by ShinokiRyosei** [comment]
Nice!
さすが
