### ISSUE TITLE
時間指定　pickerview　作成

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#15]

**Comment by sotakenmotsu** [comment]
<img width="810" alt="2017-01-23 21 45 25" src="https://cloud.githubusercontent.com/assets/19428366/22204472/8395cd8a-e1b5-11e6-956c-4c46cbeea9d2.png">
<img width="635" alt="2017-01-23 21 46 51" src="https://cloud.githubusercontent.com/assets/19428366/22204473/83971f64-e1b5-11e6-9855-f760cfdab58b.png">

よくわからないバグでた

**Comment by sotakenmotsu** [comment]
`fatal error: Index out of range`
コンソールにバグ

**Comment by ShinokiRyosei** [comment]
ただのGoogle翻訳じゃなくて、`swift`とか`xcode`ってつけて検索かける癖つけようか

**Comment by ShinokiRyosei** [comment]
そうやって検索してみるとどういうエラーか日本語か英語の記事出てくるはずだから、まずそうやって調べてエラー内容を自分の言葉で説明してみて

**Comment by sotakenmotsu** [comment]
<img width="323" alt="2017-01-24 17 51 28" src="https://cloud.githubusercontent.com/assets/19428366/22240294/d98d6b78-e25d-11e6-96b2-ff6c987844f3.png">
<img width="323" alt="2017-01-24 17 51 51" src="https://cloud.githubusercontent.com/assets/19428366/22240295/d98d80b8-e25d-11e6-956a-566045ddd623.png">

全ての`pickerview`の範囲指定が同期されてるのが原因みたい

**Comment by ShinokiRyosei** [comment]
それはエラー内容がどういうことを示してるかわかったってこと？

**Comment by ShinokiRyosei** [comment]
> 全ての`pickerview`の範囲指定が同期されてるのが原因みたい

ということは、どうすれば同期されなくなるのかな？

**Comment by sotakenmotsu** [comment]
終わった
