### ISSUE TITLE
Realmのモデルクラス定義

### ISSUE THREAD

**Issue by ShinokiRyosei** [sotakenmotsu/TennisBB#23]
どういう名前のモデル(データベースに保存するクラス)をつくって、そこに
1. どういう名前で
2. どういうデータ型の
3. どういうデータ(日付とか)を

いれるかまとめとこうか

**Comment by sotakenmotsu** [comment]
## 場所
1. place
2. String
3. 場所

## 開始時間
1. starttime
2. Int
3. 開始時間

## 終了時間
1. endtime
2. Int
3. 終了時間

## 人数
1. member
2. String
3. 人数

## レベル
1. level
2. String
3. レベル

**Comment by ShinokiRyosei** [comment]
モデル自体はどういう名前にするの？

モデルっていうのは、今回でいうとクラス名ね。

**Comment by sotakenmotsu** [comment]
'Realm'ってしてる

**Comment by sotakenmotsu** [comment]
`Data`に変えた

**Comment by ShinokiRyosei** [comment]
データだとどこで使える情報かわからないよね？
そもそも、このモデルはどういうデータのまとまりなの？

**Comment by sotakenmotsu** [comment]
`Contents`にした

**Comment by ShinokiRyosei** [comment]
OK

**Comment by ShinokiRyosei** [comment]
`Contents`だとコンテンツだから、なんのコンテンツ?って初めてそのモデルをきいた人は思うと思うけど、ギリ許容範囲の命名かな
