### ISSUE TITLE
tableview エラー

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#24]
<img width="1021" alt="2017-02-11 14 17 00" src="https://cloud.githubusercontent.com/assets/19428366/22851436/e86e7a78-f064-11e6-87e6-5e6f98debafa.png">

戻り値`UITableview`は本来の戻り値`Int`型に変換できないみたいな内容だと思う

**Comment by sotakenmotsu** [comment]
配列を作らなきゃいけないのかな？

**Comment by ShinokiRyosei** [comment]
`TableView`は配列をきれいに見せるためのものだから、配列いるね

あと、
```swift
var selectedcell: UITableViewCell!

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
     return selectedcell
}
```

って言う風にコード書いてるけど、いつもこうやってグローバル変数をつくって、それを`return`してたかい？
あと問題なのは、そもそもこういう書き方しないけど、今`selectedcell`にイコールつかって値を代入したりしてないよね？`selectedcell`常に`nil`だから毎回クラッシュしちゃうよ。`nil`かどうかにも常に意識を払おう

**Comment by sotakenmotsu** [comment]
配列をまとめるのに辞書型使うと思うんだけど、辞書型って二つしか一緒にできないの？
`String`型で５個をまとめたいんだけど

**Comment by sotakenmotsu** [comment]
全部`String`型だから`var ABarray = Aarray + Barray`でできるの？

**Comment by sotakenmotsu** [comment]
そしたら順番ごちゃごちゃでできないか

**Comment by sotakenmotsu** [comment]
<img width="793" alt="2017-02-12 17 04 59" src="https://cloud.githubusercontent.com/assets/19428366/22860578/6bb55632-f145-11e6-8196-f577ddc4814d.png">
これでできるかな？

**Comment by ShinokiRyosei** [comment]
今の言い方だと、辞書型のなにが2つしかできないと今思ってるかわからないよ。なにが2つしかできない？

```swift
var a: String = "しのき"
var b: String = "りょうせい"

var c: String = a + b // ｃの値はしのきりょうせい
```
だとできるよ。
あと、タプルは今回関係ないと思うよ

**Comment by sotakenmotsu** [comment]
辞書型だと`[String:String:String:String:String]`という形にはできないの？

**Comment by ShinokiRyosei** [comment]
辞書型の基本的な書き方覚えてるかい？

[ディクショナリ](http://tea-leaves.jp/swift/content/ディクショナリ)
keyとvalue意識してみるどうなると思う？

**Comment by ShinokiRyosei** [comment]
一回基本的な書き方ここに書いてみて

**Comment by sotakenmotsu** [comment]
```swift
var array: [String: Int] = ["いぬ": 2]
var array: Dictionary<String: String> = ["ねこ": 3]
```

**Comment by ShinokiRyosei** [comment]
そうやんな！
辞書型はキーとバリューがセットだから、5つにしたいっていうのはキーとバリューが5つずつあることになるから、

[String:String:String:String:String]っていうのは形としておかしくないかい？

**Comment by ShinokiRyosei** [comment]
あと、`array`っていうのは配列だから、
> var array = [String:String:String:String:String]()

って言う風に辞書型の変数名に`array`はやめとこう

**Comment by sotakenmotsu** [comment]
```swift
var dictionary: [String: Int, String: Int] = ["いぬ": 1, "ねこ": 2]
```
これはできるの？

**Comment by ShinokiRyosei** [comment]
辞書型を配列にいれるのは可能
