### ISSUE TITLE
Realmにidを設定する

### ISSUE THREAD

**Issue by ShinokiRyosei** [sotakenmotsu/TennisBB#31]
https://github.com/ShinokiRyosei/Realm-Sampler/blob/master/Realm-Sampler/Model/ToDoModel.swift

**Comment by sotakenmotsu** [comment]
使うのって`loadAll`のところだけ？

**Comment by sotakenmotsu** [comment]
http://qiita.com/_ha1f/items/f6318e326434dbf83037
このページ通りにやればいいの？

**Comment by ShinokiRyosei** [comment]
`lastId`やね

**Comment by sotakenmotsu** [comment]
`lastId`だけ追加したら、落ちたよ

**Comment by ShinokiRyosei** [comment]
`lastId()`使ってる？
