### ISSUE TITLE
オプショナルバインディング

### ISSUE THREAD

**Issue by ShinokiRyosei** [sotakenmotsu/TennisBB#32]
`guard`か`if let`文使って、`nil`のときにデータを保存しないようにする
https://github.com/sotakenmotsu/TennisBB/blob/master/TennisBB/RContentsViewController.swift#L202-L207

**Comment by sotakenmotsu** [comment]
このメソッドに`nil`時に保存しないコードを書くの？

**Comment by sotakenmotsu** [comment]
そもそもまだこのメソッド使われてない

**Comment by sotakenmotsu** [comment]
これ`textview`以外をタッチすると閉じるメソッドだと思うんだけど

**Comment by ShinokiRyosei** [comment]
前までは正しいところハイライトしてくれたのに、コードの場所変わってハイライトされてるコードが変わってしまった

**Comment by ShinokiRyosei** [comment]
https://github.com/sotakenmotsu/TennisBB/blob/master/TennisBB/RContentsViewController.swift#L225-L235

**Comment by ShinokiRyosei** [comment]
こっちや

そうそう`PlaceView`とかのユーザーがデータを入れるところのデータが`nil`のときに保存しないようにコード加工

**Comment by sotakenmotsu** [comment]
わかった

**Comment by ShinokiRyosei** [comment]
👍

**Comment by sotakenmotsu** [comment]
アラートが出たあとすぐ消えちゃう

**Comment by sotakenmotsu** [comment]
完全に解決した

**Comment by sotakenmotsu** [comment]
<img width="322" alt="2017-05-31 18 39 59" src="https://cloud.githubusercontent.com/assets/19428366/26626038/e10aefec-4630-11e7-9d04-f1cf363366ad.png">
