### ISSUE TITLE
tableview大きさ調整する

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#35]
<img width="321" alt="2017-06-06 20 38 03" src="https://cloud.githubusercontent.com/assets/19428366/26827412/1dd3950c-4af8-11e7-96c2-658e21ae1a2f.png">
<img width="321" alt="2017-06-06 20 38 15" src="https://cloud.githubusercontent.com/assets/19428366/26827414/1df5d6d0-4af8-11e7-9506-ea9f9e37ebd2.png">
上と下が被ってる

**Comment by sotakenmotsu** [comment]
`tableviewcontroller`を使ってても大きさを変えられるの？

**Comment by ShinokiRyosei** [comment]
`NavigationController`とかで`NavigationBar`を設定する以外はできないと思う

**Comment by ShinokiRyosei** [comment]
基本的に画面いっぱいに`TableView`を設定されてるのが、`UITableViewController`

**Comment by sotakenmotsu** [comment]
下はまあいいとして上もどうにかならないの？

**Comment by ShinokiRyosei** [comment]
上部に`NavigationController`使って`NavigationBar`設定しよう
ストーリーボードでね！

**Comment by sotakenmotsu** [comment]
<img width="320" alt="2017-06-10 21 25 10" src="https://user-images.githubusercontent.com/19428366/27002723-5d1b31a6-4e23-11e7-9e31-dc376cd14643.png">
<img width="178" alt="2017-06-10 21 25 30" src="https://user-images.githubusercontent.com/19428366/27002724-5d1bcbfc-4e23-11e7-9c89-de4240a0d460.png">
これでいいの？できたっぽいけど

**Comment by ShinokiRyosei** [comment]
YES!
