### ISSUE TITLE
storyboard 消えた

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#41]
消えちゃったんだけど、作り直すしかないの？

**Comment by sotakenmotsu** [comment]
<img width="341" alt="2017-07-06 17 07 43" src="https://user-images.githubusercontent.com/19428366/27901615-a8d670ca-626d-11e7-9af3-9fa2d9d0d71e.png">
こういう感じで、何も出てこない

**Comment by ShinokiRyosei** [comment]
それゴミ箱に捨てちゃったんじゃない？
それかファインダーのプロジェクトフォルダに入ってるけど、Xcodeが読み込んでないだけか

**Comment by sotakenmotsu** [comment]
ゴミ箱からにしちゃった

**Comment by sotakenmotsu** [comment]
<img width="771" alt="2017-07-06 17 28 10" src="https://user-images.githubusercontent.com/19428366/27902376-8455b0e6-6270-11e7-9de9-5dd9ea09a850.png">

**Comment by sotakenmotsu** [comment]
完全に消えたっぽい

**Comment by ShinokiRyosei** [comment]
作り直しやねwww

**Comment by ShinokiRyosei** [comment]
ファイト！

**Comment by ShinokiRyosei** [comment]
いやコミット履歴から過去に遡ればいい！

**Comment by ShinokiRyosei** [comment]
そのかわりいまの作業内容は消えるけど、そっちのほうがはやいと思う
ちょい履歴の遡り方ググって頑張ってみて

**Comment by sotakenmotsu** [comment]
http://seeku.hateblo.jp/entry/2016/03/02/232151
http://inari.hatenablog.com/entry/2014/05/18/002355
これとかやってみたけど、直らないんだけど、、、

**Comment by ShinokiRyosei** [comment]
http://inari.hatenablog.com/entry/2014/05/18/002355

**Comment by ShinokiRyosei** [comment]
こっちは合ってるよ
どういうコマンド打った？

**Comment by sotakenmotsu** [comment]
<img width="571" alt="2017-07-06 20 31 06" src="https://user-images.githubusercontent.com/19428366/27909126-29463300-628a-11e7-85b0-ab01d9adf9fc.png">
この後なんか必要？

**Comment by sotakenmotsu** [comment]
'git pull origin master'って打つの？

**Comment by ShinokiRyosei** [comment]
いやそのままでいい

**Comment by ShinokiRyosei** [comment]
`git push -f origin master`次にこれを打つ

**Comment by sotakenmotsu** [comment]
直らないよー

**Comment by ShinokiRyosei** [comment]
それは履歴もっと戻さないとあかんのじゃない？
履歴をどこまで戻すで直るか治らんか決まる？

**Comment by sotakenmotsu** [comment]
このコミットの時はRunもしたし、まだ消えてなかったと思うんだけど

**Comment by ShinokiRyosei** [comment]
いやそのコミットの状態が今のgithubの状態やけど、`Main.storyboard`すでにないよ

ほら！ 👇 
<img width="333" alt="2017-07-07 1 12 51" src="https://user-images.githubusercontent.com/11238461/27921044-7b8578d4-62b1-11e7-8c2f-10d93f8e7f4a.png">

**Comment by sotakenmotsu** [comment]
ストーリーボード以外戻ってる
これが原因👇？
<img width="213" alt="2017-07-07 17 03 35" src="https://user-images.githubusercontent.com/19428366/27948902-795484da-6336-11e7-9cd3-9d0ba58981ec.png">

**Comment by ShinokiRyosei** [comment]
xcodeプロジェクトはファイルを参照してるっぽいね

**Comment by ShinokiRyosei** [comment]
コミット履歴もっと遡らんとあかんかもね
遡りすぎると書いたコードなくなるから、遡りすぎるのもめんどいけどね笑

**Comment by sotakenmotsu** [comment]
<img width="1280" alt="2017-07-08 16 35 37" src="https://user-images.githubusercontent.com/19428366/27983595-8a13755e-63fb-11e7-9c38-dbb32544bc8e.png">
もう一個前で戻ったー！
あとはgithub見ながらやり直せばいいんだよね

**Comment by ShinokiRyosei** [comment]
そうそう！
あとは最後にプッシュするときは、
git push -f origin masterね

**Comment by sotakenmotsu** [comment]
<img width="724" alt="2017-07-12 22 10 26" src="https://user-images.githubusercontent.com/19428366/28119232-0c324028-674f-11e7-8e69-b7a84131865d.png">
<img width="153" alt="2017-07-12 22 10 34" src="https://user-images.githubusercontent.com/19428366/28119231-0c311ae0-674f-11e7-9f56-998ad199c34a.png">
<img width="827" alt="2017-07-12 22 10 46" src="https://user-images.githubusercontent.com/19428366/28119230-0c2d877c-674f-11e7-8167-f1574e0a62a0.png">
サイトに載ってたコードがエラー出てるんだけど、、

**Comment by ShinokiRyosei** [comment]
サイトのリンクは？

**Comment by ShinokiRyosei** [comment]
スクショだけやと、前後でなにをしないといけないかわからないから、サポートしようにも「うん。コードは同じように書いてるけど、クラッシュするね。で、それ以外の部分は合ってる？」っていう確認しかおれにはできない

**Comment by sotakenmotsu** [comment]
http://dev.classmethod.jp/smartphone/xib/
ごめんごめん、リンクはこれなんだけど

**Comment by ShinokiRyosei** [comment]
ありがとう

**Comment by ShinokiRyosei** [comment]
今の状態でプッシュしてくれる？

**Comment by ShinokiRyosei** [comment]
プッシュするときにコミットメッセージつけないとgithubにうまく上がらないからもう一回ちゃんとコミットメッセージつけてプッシュして

コードのどっかで空行とかいれるとコミットできると思うから、それでコミットしてプッシュしてみて

**Comment by sotakenmotsu** [comment]
コミットとプッシュしたよー

**Comment by ShinokiRyosei** [comment]
ターミナルで
```
git add Podfile
git add Podfile.lock
git commit -m 'Add Podfile'
git push origin master
```
やってみて

**Comment by ShinokiRyosei** [comment]
無限に循環してるね
<img width="239" alt="2017-07-14 23 47 08" src="https://user-images.githubusercontent.com/11238461/28217094-e28e00f8-68ee-11e7-8248-c876fc6f24d7.png">

**Comment by ShinokiRyosei** [comment]
[これ](https://github.com/sotakenmotsu/TennisBB/compare/master...shinoki)見るか、`shinoki`っていうブランチ見て、直してみ

**Comment by sotakenmotsu** [comment]
<img width="346" alt="2017-07-17 9 32 56" src="https://user-images.githubusercontent.com/19428366/28252685-f5e92426-6ad2-11e7-8028-200c9decf11c.png">
直したらこのエラーが出た

**Comment by ShinokiRyosei** [comment]
今プッシュしてあって、最新状態？

**Comment by ShinokiRyosei** [comment]
これみて直してみて！
<img width="1152" alt="2017-07-19 14 09 47" src="https://user-images.githubusercontent.com/11238461/28351611-fb913f66-6c8b-11e7-8997-b4debff6d36f.png">

**Comment by sotakenmotsu** [comment]
<img width="1035" alt="2017-08-06 23 05 10" src="https://user-images.githubusercontent.com/19428366/29003994-c1d2b2ea-7afb-11e7-8288-cd4eca30c982.png">
こうするってこと？
<img width="353" alt="2017-08-06 23 05 19" src="https://user-images.githubusercontent.com/19428366/29004004-dd6687fc-7afb-11e7-874e-72a5f6e8426c.png">
これだとこのバグ出るけど

**Comment by ShinokiRyosei** [comment]
それってプッシュされてる？
こっちだときちんと動いてるんだよね。プッシュしてくれたら見る！

**Comment by sotakenmotsu** [comment]
プッシュしたよ

**Comment by ShinokiRyosei** [comment]
見た！
File's Ownerのクラスに`HeaderView`を指定してるのが良くないね。クラス指定消して、そこから関連付けも消そう

<img width="1424" alt="2017-08-08 4 33 17" src="https://user-images.githubusercontent.com/11238461/29042672-db34b15a-7bf2-11e7-803b-d33b2abf0ca8.png">
<img width="1421" alt="2017-08-08 4 33 24" src="https://user-images.githubusercontent.com/11238461/29042673-db361eb4-7bf2-11e7-8ad7-e6f6c1e179d9.png">

**Comment by sotakenmotsu** [comment]
<img width="327" alt="2017-08-08 11 03 23" src="https://user-images.githubusercontent.com/19428366/29053132-3b7404a4-7c29-11e7-973c-0f796ebea810.png">
できたー！

**Comment by ShinokiRyosei** [comment]
Good Job! Nice!!!
