### ISSUE TITLE
ログイン機能を実装

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#45]
https://qiita.com/ShinokiRyosei/items/f71c73ab8b0de145c5bc

**Comment by sotakenmotsu** [comment]
Realm関係は全部消しちゃっていいの？

**Comment by ShinokiRyosei** [comment]
Realm消しても、クラス自体は残しといてね

**Comment by sotakenmotsu** [comment]
クラスを残すっていうのは、コードは残しとけってこと？
一旦全部スラッシュしとくけど

**Comment by ShinokiRyosei** [comment]
いや違う
```swift

import RealmSwift
class Dog: Object {
}
```
ってなってるのを、importとObjectクラスへの継承を消す。 👇 
```swift
class Dog {
}
```

それで、overrideってなってるコードを消す
