### ISSUE TITLE
HEADからmasterにコミットを移す

### ISSUE THREAD

**Issue by ShinokiRyosei** [sotakenmotsu/TennisBB#46]
https://stackoverflow.com/questions/1356112/how-to-merge-head-commits-from-another-branch

**Comment by sotakenmotsu** [comment]
http://oki2a24.com/2016/01/30/use-git-stash-when-can-not-checkout/
このページみてやってみたら、`HEAD`が`new-feature`になったけど、`Mainstoryboard`が開けなくなった

**Comment by ShinokiRyosei** [comment]
`new-feature`を`master`にマージするだけでいいんちゃうかな
新しくコミットする必要はないと思うけど、

多分swiftのなかのファイルが出てきちゃってるね

Source Treeで今のコミットの履歴がどうなってるか見せて

**Comment by sotakenmotsu** [comment]
<img width="952" alt="2017-11-04 17 10 32" src="https://user-images.githubusercontent.com/19428366/32403667-16ea7952-c183-11e7-9bab-f59a6acdd995.png">
こんな感じ

**Comment by sotakenmotsu** [comment]
<img width="567" alt="2017-11-04 17 11 41" src="https://user-images.githubusercontent.com/19428366/32403675-41d4971a-c183-11e7-9fe9-4d9409dca19b.png">
`new-feature`が`checkout`できない

**Comment by ShinokiRyosei** [comment]
new featureをpushして、github上でpull requestをつくろうか

**Comment by ShinokiRyosei** [comment]
あと、今masterに差分でてるから、その差分が必要のない、変更した覚えがないものなら、`git reset --hard`で消しちゃおう

**Comment by sotakenmotsu** [comment]
<img width="844" alt="2017-11-05 21 57 40" src="https://user-images.githubusercontent.com/19428366/32414942-65a403be-c274-11e7-9172-cb7f6611a0bf.png">
pull requestやったことないけど、これでいいの？

**Comment by sotakenmotsu** [comment]
<img width="579" alt="2017-11-05 21 55 04" src="https://user-images.githubusercontent.com/19428366/32414968-ac98543c-c274-11e7-8861-7c12eac0d872.png">
これでプッシュできてる？

**Comment by ShinokiRyosei** [comment]
できてる！
プルリクつくろう！

**Comment by ShinokiRyosei** [comment]
@sotakenmotsu 
もっかいプルリクつくってマージしよう

**Comment by ShinokiRyosei** [comment]
できたら、Source Treeでpullね
