### ISSUE TITLE
Contentの扱い

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#50]
<img width="738" alt="2017-11-07 22 28 32" src="https://user-images.githubusercontent.com/19428366/32495965-0646e8d0-c40b-11e7-90e7-28391baf195e.png">
この写真みたいな、 Realmを消してでたエラーを解消したい
このせいでRunできない

**Comment by ShinokiRyosei** [comment]
Contentクラスからプロパティを消す必要はないよ
try! realmみたいなRealmを使ってるコードは消していい
