### ISSUE TITLE
sshをhttpにする

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#51]

**Comment by sotakenmotsu** [comment]
<img width="591" alt="2017-11-21 22 21 02" src="https://user-images.githubusercontent.com/19428366/33074649-4ad31226-cf0a-11e7-955a-6d476c4293c4.png">
今こんな感じ

**Comment by ShinokiRyosei** [comment]
https://qiita.com/konitter/items/71da5b9b40c1d20a6a11

**Comment by sotakenmotsu** [comment]
<img width="496" alt="2017-11-28 18 00 20" src="https://user-images.githubusercontent.com/19428366/33310771-0ffba846-d466-11e7-9aed-b336e6b33990.png">
