### ISSUE TITLE
databaseにBoard情報を入力できるようにする

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#52]

**Comment by sotakenmotsu** [comment]
<img width="998" alt="2017-12-21 21 33 05" src="https://user-images.githubusercontent.com/19428366/34256006-90c10394-e696-11e7-9657-af49a727af84.png">
`nil`の判定が悪いことはわかったんだけど、直しかたがわからない
この中の`!`の使い方が悪いのかな？

**Comment by sotakenmotsu** [comment]
<img width="440" alt="2017-12-22 13 57 42" src="https://user-images.githubusercontent.com/19428366/34285833-1eaee480-e720-11e7-99ae-145daa514c3e.png">
この部分を`if Placeview != nil {`に変えるってこと？

**Comment by ShinokiRyosei** [comment]
いや追加する
nilでもダメ出し、""で文字なしでもダメだよね？

**Comment by sotakenmotsu** [comment]
ここで落ちた時は、全部の項目に記入して投稿ボタン押したけど、仮に全部値が入っててもnilチェックは必要ってこと？

**Comment by ShinokiRyosei** [comment]
そうしちゃうとboardのスコープ違うよ

まず、おれが言いたかったのは、
```swift
if PlaceView.text == "" || PlaceView.text == nil {
}
```
って言う風に「または」それぞれの入力欄に条件つけてっていう意味ね

**Comment by ShinokiRyosei** [comment]
で、今出てるエラーは、`board`を宣言してるブロック(波括弧の範囲)の外では、`board`は使えないよ

変数のスコープっていう概念ね
宣言されてる波括弧の外では、変数も関数も使えないよ

**Comment by sotakenmotsu** [comment]
```swift
PlaceView.text ==  ""
```
と
```swift
PlaceView.text == nil
```
って何が違うの？

**Comment by sotakenmotsu** [comment]
<img width="945" alt="2017-12-23 11 32 18" src="https://user-images.githubusercontent.com/19428366/34316280-07a37606-e7d5-11e7-81d0-5e7205dc6aa9.png">
全部nilチェックのコード書いたけどエラーでた

**Comment by ShinokiRyosei** [comment]
そういうこと

**Comment by ShinokiRyosei** [comment]
正確には、入力欄のnilはないことになる。
あとはもしそれでも落ちたら、キャストとかの問題になるね
