### ISSUE TITLE
データ削除機能を実装する

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#55]

**Comment by sotakenmotsu** [comment]
<img width="580" alt="2018-01-31 22 15 24" src="https://user-images.githubusercontent.com/19428366/35625056-47f4a6d0-06d4-11e8-808c-7d64365f80ec.png">
この動作削除とか編集でも使いたいんだけど、メソッド化して使える？

**Comment by ShinokiRyosei** [comment]
削除したあとに、データを取得する必要なくない？

**Comment by sotakenmotsu** [comment]
リロードできればいいか

**Comment by ShinokiRyosei** [comment]
ローカルのほうの配列から削除か編集されていれば、それをリモートに反映すれば、ローカルとリモートの状態同じになるから、取得まではしなくてよい

**Comment by sotakenmotsu** [comment]
よく考えたら`LookforViewController`からデータ消す必要なかった
`RContentsViewController`から削除編集できるようにしたい
