### ISSUE TITLE
HeaderView上にbackとeditのボタンをつける

### ISSUE THREAD

**Issue by sotakenmotsu** [sotakenmotsu/TennisBB#59]

**Comment by sotakenmotsu** [comment]
https://qiita.com/0x20FE/items/740a49dbe8899a85fa02
このページとかみてるけど、`HeaderView`上のボタンから戻る方法がわからない

**Comment by ShinokiRyosei** [comment]
一旦`LContentsViewController`とか、`VEViewController`とかの名前もっとわかりやすい省略してない名前に変えて。
それがなにをする画面なのか名前からわからないから、質問に答えづらい

**Comment by sotakenmotsu** [comment]
名前変えてみたよ

**Comment by ShinokiRyosei** [comment]
あざす！
ViewControllerをVCって略してるのもダメね。
略すメリットなにもないから、やめとこう

HeaderViewCellViewControllerってCellなの？ViewControllerなの？

**Comment by ShinokiRyosei** [comment]
話を戻すと、NavigationController使ってないの？

あと、HeaderViewのなかにあるなら、関連付けできるのはHeaderViewからで、ViewControllerからはムリ

**Comment by ShinokiRyosei** [comment]
https://github.com/sotakenmotsu/TennisBB/commit/06168f67eac67fb12372ff441b9d0c76f376eb9b

**Comment by sotakenmotsu** [comment]
ボタンと画面遷移は両方できた
